version: "3.8"

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    #restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql:
  postgresql_data: